import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    dom: "src/dom/index.ts",
    adapters: "src/adapters/index.ts",
    react: "src/react/index.tsx",
    "react-native": "src/react-native/index.tsx",
    vue: "src/vue/index.ts",
    // The astro entry (dist/MorphIcon.astro + astro.d.ts) is generated by
    // scripts/build-astro.ts after tsdown: the .astro shell ships as source
    // (the consumer's Astro compiles it) over the element chunk.
    element: "src/element/index.ts",
    // The svelte entry itself (dist/svelte.js + .d.ts + MorphIcon.svelte) is
    // generated by scripts/build-svelte.ts after tsdown: a .svelte component
    // ships as source (the consumer's bundler compiles it) and only its TS
    // half goes through the bundler.
    "svelte-shared": "src/svelte/shared.ts",
  },
  format: "esm",
  platform: "neutral",
  target: "es2022",
  // Build/dts only (jsx + lib DOM for the binding). The rule "core and
  // driver compile without DOM" is still enforced by `bun run typecheck`.
  tsconfig: "tsconfig.build.json",
  dts: true,
  clean: true,
});
