/* Icon registry for the studio: a curated Lucide set imported live from the
   `lucide` data package, plus Feather and Tabler icons vendored from the
   morphicons playground (Feather v4.29.2 MIT, Tabler v3.46.0 MIT). All three
   draw on a 24x24 grid, which is why cross-library morphs just work. */

import {
  Activity,
  Aperture,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Bookmark,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  Clock,
  Cloud,
  Code,
  Copy,
  Diamond,
  Download,
  Eye,
  EyeOff,
  Folder,
  Gift,
  GitBranch,
  Globe,
  Heart,
  House,
  Info,
  Layers,
  LayoutGrid,
  List,
  Lock,
  LockOpen,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Mic,
  Minus,
  Moon,
  Package,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Repeat,
  Search,
  Send,
  Settings,
  Shuffle,
  Square,
  Star,
  Sun,
  Terminal,
  ThumbsUp,
  Trash2,
  TrendingUp,
  Triangle,
  Upload,
  User,
  Users,
  Volume2,
  Wifi,
  X,
  Zap,
} from "lucide";
import type { IconInput, IconNode } from "morphicons";
import { cubicsToPathD, iconToCubics } from "morphicons";

export type Lib = "lucide" | "feather" | "tabler";

export interface IconEntry {
  id: string;
  /** Searchable, human name ("arrow-right"). */
  label: string;
  lib: Lib;
  data: IconInput;
  /** For codegen: the named export in the `lucide` package, if any. */
  lucideExport?: string;
}

const LUCIDE: Record<string, [string, IconInput]> = {
  menu: ["Menu", Menu],
  x: ["X", X],
  check: ["Check", Check],
  plus: ["Plus", Plus],
  minus: ["Minus", Minus],
  "arrow-right": ["ArrowRight", ArrowRight],
  "arrow-down": ["ArrowDown", ArrowDown],
  "arrow-left": ["ArrowLeft", ArrowLeft],
  "arrow-up": ["ArrowUp", ArrowUp],
  "chevron-down": ["ChevronDown", ChevronDown],
  "chevron-right": ["ChevronRight", ChevronRight],
  square: ["Square", Square],
  circle: ["Circle", Circle],
  diamond: ["Diamond", Diamond],
  triangle: ["Triangle", Triangle],
  heart: ["Heart", Heart],
  star: ["Star", Star],
  bell: ["Bell", Bell],
  settings: ["Settings", Settings],
  camera: ["Camera", Camera],
  sun: ["Sun", Sun],
  moon: ["Moon", Moon],
  search: ["Search", Search],
  play: ["Play", Play],
  pause: ["Pause", Pause],
  aperture: ["Aperture", Aperture],
  house: ["House", House],
  zap: ["Zap", Zap],
  copy: ["Copy", Copy],
  download: ["Download", Download],
  upload: ["Upload", Upload],
  trash: ["Trash2", Trash2],
  pencil: ["Pencil", Pencil],
  eye: ["Eye", Eye],
  "eye-off": ["EyeOff", EyeOff],
  lock: ["Lock", Lock],
  "lock-open": ["LockOpen", LockOpen],
  mail: ["Mail", Mail],
  user: ["User", User],
  users: ["Users", Users],
  calendar: ["Calendar", Calendar],
  clock: ["Clock", Clock],
  cloud: ["Cloud", Cloud],
  wifi: ["Wifi", Wifi],
  bookmark: ["Bookmark", Bookmark],
  folder: ["Folder", Folder],
  send: ["Send", Send],
  "thumbs-up": ["ThumbsUp", ThumbsUp],
  "message-circle": ["MessageCircle", MessageCircle],
  info: ["Info", Info],
  "map-pin": ["MapPin", MapPin],
  globe: ["Globe", Globe],
  refresh: ["RefreshCw", RefreshCw],
  volume: ["Volume2", Volume2],
  mic: ["Mic", Mic],
  repeat: ["Repeat", Repeat],
  shuffle: ["Shuffle", Shuffle],
  terminal: ["Terminal", Terminal],
  code: ["Code", Code],
  "git-branch": ["GitBranch", GitBranch],
  package: ["Package", Package],
  gift: ["Gift", Gift],
  "trending-up": ["TrendingUp", TrendingUp],
  activity: ["Activity", Activity],
  layers: ["Layers", Layers],
  "layout-grid": ["LayoutGrid", LayoutGrid],
  list: ["List", List],
};

/* Vendored from playground/vendor-icons.ts (generated by
   extract-vendor-icons.mjs). Feather Icons v4.29.2 (MIT). */
const FEATHER: Record<string, IconNode> = {
  camera: [
    ["path", { d: "M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" }],
    ["circle", { cx: "12", cy: "13", r: "4" }],
  ],
  github: [
    ["path", { d: "M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22" }],
  ],
  settings: [
    ["circle", { cx: "12", cy: "12", r: "3" }],
    ["path", { d: "M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z" }],
  ],
  scissors: [
    ["circle", { cx: "6", cy: "6", r: "3" }],
    ["circle", { cx: "6", cy: "18", r: "3" }],
    ["line", { x1: "20", y1: "4", x2: "8.12", y2: "15.88" }],
    ["line", { x1: "14.47", y1: "14.48", x2: "20", y2: "20" }],
    ["line", { x1: "8.12", y1: "8.12", x2: "12", y2: "12" }],
  ],
  coffee: [
    ["path", { d: "M18 8h1a4 4 0 0 1 0 8h-1" }],
    ["path", { d: "M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z" }],
    ["line", { x1: "6", y1: "1", x2: "6", y2: "4" }],
    ["line", { x1: "10", y1: "1", x2: "10", y2: "4" }],
    ["line", { x1: "14", y1: "1", x2: "14", y2: "4" }],
  ],
  wifi: [
    ["path", { d: "M5 12.55a11 11 0 0 1 14.08 0" }],
    ["path", { d: "M1.42 9a16 16 0 0 1 21.16 0" }],
    ["path", { d: "M8.53 16.11a6 6 0 0 1 6.95 0" }],
    ["line", { x1: "12", y1: "20", x2: "12.01", y2: "20" }],
  ],
  "cloud-rain": [
    ["line", { x1: "16", y1: "13", x2: "16", y2: "21" }],
    ["line", { x1: "8", y1: "13", x2: "8", y2: "21" }],
    ["line", { x1: "12", y1: "15", x2: "12", y2: "23" }],
    ["path", { d: "M20 16.58A5 5 0 0 0 18 7h-1.26A8 8 0 1 0 4 15.25" }],
  ],
  feather: [
    ["path", { d: "M20.24 12.24a6 6 0 0 0-8.49-8.49L5 10.5V19h8.5z" }],
    ["line", { x1: "16", y1: "8", x2: "2", y2: "22" }],
    ["line", { x1: "17.5", y1: "15", x2: "9", y2: "15" }],
  ],
};

/* Tabler Icons v3.46.0 (MIT). */
const TABLER: Record<string, IconNode> = {
  cat: [
    ["path", { d: "M20 3v10a8 8 0 1 1 -16 0v-10l3.432 3.432a7.963 7.963 0 0 1 4.568 -1.432c1.769 0 3.403 .574 4.728 1.546l3.272 -3.546" }],
    ["path", { d: "M2 16h5l-4 4" }],
    ["path", { d: "M22 16h-5l4 4" }],
    ["path", { d: "M11 16a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" }],
    ["path", { d: "M9 11v.01" }],
    ["path", { d: "M15 11v.01" }],
  ],
  ghost: [
    ["path", { d: "M5 11a7 7 0 0 1 14 0v7a1.78 1.78 0 0 1 -3.1 1.4a1.65 1.65 0 0 0 -2.6 0a1.65 1.65 0 0 1 -2.6 0a1.65 1.65 0 0 0 -2.6 0a1.78 1.78 0 0 1 -3.1 -1.4v-7" }],
    ["path", { d: "M10 10l.01 0" }],
    ["path", { d: "M14 10l.01 0" }],
    ["path", { d: "M10 14a3.5 3.5 0 0 0 4 0" }],
  ],
  planet: [
    ["path", { d: "M18.816 13.58c2.292 2.138 3.546 4 3.092 4.9c-.745 1.46 -5.783 -.259 -11.255 -3.838c-5.47 -3.579 -9.304 -7.664 -8.56 -9.123c.464 -.91 2.926 -.444 5.803 .805" }],
    ["path", { d: "M5 12a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" }],
  ],
  rocket: [
    ["path", { d: "M4 13a8 8 0 0 1 7 7a6 6 0 0 0 3 -5a9 9 0 0 0 6 -8a3 3 0 0 0 -3 -3a9 9 0 0 0 -8 6a6 6 0 0 0 -5 3" }],
    ["path", { d: "M7 14a6 6 0 0 0 -3 6a6 6 0 0 0 6 -3" }],
    ["path", { d: "M14 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" }],
  ],
  bolt: [["path", { d: "M13 3l0 7l6 0l-8 11l0 -7l-6 0l8 -11" }]],
  "brand-github": [
    ["path", { d: "M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5" }],
  ],
  bike: [
    ["path", { d: "M2 18a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" }],
    ["path", { d: "M16 18a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" }],
    ["path", { d: "M12 19v-4l-3 -3l5 -4l2 3h3" }],
    ["path", { d: "M13.007 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" }],
  ],
  "moon-stars": [
    ["path", { d: "M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454l0 .008" }],
    ["path", { d: "M17 4a2 2 0 0 0 2 2a2 2 0 0 0 -2 2a2 2 0 0 0 -2 -2a2 2 0 0 0 2 -2" }],
    ["path", { d: "M19 11h2m-1 -1v2" }],
  ],
};

export const ICONS: IconEntry[] = [
  ...Object.entries(LUCIDE).map(([label, [exp, data]]) => ({
    id: `lucide:${label}`,
    label,
    lib: "lucide" as const,
    data,
    lucideExport: exp,
  })),
  ...Object.entries(FEATHER).map(([label, data]) => ({
    id: `feather:${label}`,
    label,
    lib: "feather" as const,
    data,
  })),
  ...Object.entries(TABLER).map(([label, data]) => ({
    id: `tabler:${label}`,
    label,
    lib: "tabler" as const,
    data,
  })),
];

export const byId = new Map(ICONS.map((e) => [e.id, e]));

/* Canonical `d` per entry, straight from the pure core (no DOM, SSR-safe).
   Numbers are quantized to 4 decimals: arc normalization uses trig whose last
   ulp can differ between the server's V8 and the browser's, and hydration
   compares the attribute byte by byte. 1e-4 on a 24px grid is far below
   anything visible. */
const q = (d: string): string =>
  d.replace(/-?\d+\.\d+(?:e-?\d+)?/gi, (n) => String(Number(Number(n).toFixed(4))));

const dCache = new Map<string, string>();
export function dOf(entry: IconEntry): string {
  let d = dCache.get(entry.id);
  if (!d) {
    d =
      typeof entry.data === "string"
        ? entry.data
        : q(cubicsToPathD(iconToCubics(entry.data)));
    dCache.set(entry.id, d);
  }
  return d;
}
