/* Icon registry for the studio: a curated Lucide set imported live from the
   `lucide` data package, plus Heroicons (24/outline) and Tabler icons
   extracted from their npm packages into lib/vendor-icons.ts by
   scripts/extract-vendor-icons.mjs. All three draw on a 24x24 grid, which is
   why cross-library morphs just work. The selection follows the classic
   most-used-icons canon (search, home, user, menu, arrows, bell, cart…) plus
   each pack's distinctive voice. */

import {
  Activity,
  Anchor,
  Aperture,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  Battery,
  Bell,
  Bluetooth,
  Bookmark,
  Bug,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleQuestionMark,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Copy,
  Cpu,
  CreditCard,
  Database,
  Diamond,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  Feather,
  FileText,
  Film,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  Funnel,
  Gift,
  GitBranch,
  Globe,
  Headphones,
  Heart,
  House,
  Image,
  Info,
  Key,
  Layers,
  LayoutGrid,
  Link,
  List,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Mic,
  Minus,
  Monitor,
  Moon,
  Music,
  Package,
  Palette,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  Play,
  Plus,
  Printer,
  RefreshCw,
  Repeat,
  Rocket,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShoppingCart,
  Shuffle,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sparkles,
  Square,
  Star,
  Sun,
  Tag,
  Terminal,
  ThumbsUp,
  Trash2,
  TrendingUp,
  Triangle,
  TriangleAlert,
  Umbrella,
  Upload,
  User,
  Users,
  Volume2,
  VolumeX,
  Wifi,
  Wrench,
  X,
  Zap,
} from "lucide";
import type { IconInput } from "morphicons";
import { cubicsToPathD, iconToCubics } from "morphicons";
import { HEROICONS, TABLER } from "./vendor-icons";

export type Lib = "lucide" | "heroicons" | "tabler";

export interface IconEntry {
  id: string;
  /** Searchable, human name ("arrow-right"). */
  label: string;
  lib: Lib;
  data: IconInput;
}

const LUCIDE: Record<string, IconInput> = {
  menu: Menu,
  x: X,
  check: Check,
  plus: Plus,
  minus: Minus,
  "arrow-right": ArrowRight,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  square: Square,
  circle: Circle,
  diamond: Diamond,
  triangle: Triangle,
  heart: Heart,
  star: Star,
  bell: Bell,
  settings: Settings,
  camera: Camera,
  sun: Sun,
  moon: Moon,
  search: Search,
  play: Play,
  pause: Pause,
  aperture: Aperture,
  house: House,
  zap: Zap,
  copy: Copy,
  download: Download,
  upload: Upload,
  trash: Trash2,
  pencil: Pencil,
  eye: Eye,
  "eye-off": EyeOff,
  lock: Lock,
  "lock-open": LockOpen,
  key: Key,
  shield: Shield,
  mail: Mail,
  phone: Phone,
  user: User,
  users: Users,
  smile: Smile,
  calendar: Calendar,
  clock: Clock,
  cloud: Cloud,
  wifi: Wifi,
  bluetooth: Bluetooth,
  battery: Battery,
  bookmark: Bookmark,
  folder: Folder,
  "folder-open": FolderOpen,
  file: FileText,
  clipboard: Clipboard,
  printer: Printer,
  save: Save,
  send: Send,
  share: Share2,
  link: Link,
  "external-link": ExternalLink,
  paperclip: Paperclip,
  "thumbs-up": ThumbsUp,
  "message-circle": MessageCircle,
  info: Info,
  help: CircleQuestionMark,
  alert: CircleAlert,
  warning: TriangleAlert,
  ellipsis: Ellipsis,
  "map-pin": MapPin,
  globe: Globe,
  compass: Compass,
  flag: Flag,
  refresh: RefreshCw,
  volume: Volume2,
  "volume-x": VolumeX,
  mic: Mic,
  repeat: Repeat,
  shuffle: Shuffle,
  music: Music,
  film: Film,
  image: Image,
  monitor: Monitor,
  smartphone: Smartphone,
  headphones: Headphones,
  filter: Funnel,
  sliders: SlidersHorizontal,
  tag: Tag,
  "shopping-cart": ShoppingCart,
  "credit-card": CreditCard,
  "log-in": LogIn,
  "log-out": LogOut,
  terminal: Terminal,
  code: Code,
  "git-branch": GitBranch,
  bug: Bug,
  database: Database,
  server: Server,
  cpu: Cpu,
  wrench: Wrench,
  package: Package,
  gift: Gift,
  award: Award,
  "trending-up": TrendingUp,
  activity: Activity,
  layers: Layers,
  "layout-grid": LayoutGrid,
  list: List,
  sparkles: Sparkles,
  rocket: Rocket,
  flame: Flame,
  palette: Palette,
  feather: Feather,
  scissors: Scissors,
  umbrella: Umbrella,
  anchor: Anchor,
  coffee: Coffee,
};

export const ICONS: IconEntry[] = [
  ...Object.entries(LUCIDE).map(([label, data]) => ({
    id: `lucide:${label}`,
    label,
    lib: "lucide" as const,
    data,
  })),
  ...Object.entries(HEROICONS).map(([label, data]) => ({
    id: `heroicons:${label}`,
    label,
    lib: "heroicons" as const,
    data,
  })),
  ...Object.entries(TABLER).map(([label, data]) => ({
    id: `tabler:${label}`,
    label,
    lib: "tabler" as const,
    data,
  })),
];

export const byId = new Map(ICONS.map((e) => [e.id, e]));

/* Canonical `d` per entry, straight from the pure core (no DOM, SSR-safe).
   Numbers are quantized to 4 decimals: arc normalization uses trig whose last
   ulp can differ between the server's V8 and the browser's, and hydration
   compares the attribute byte by byte. 1e-4 on a 24px grid is far below
   anything visible. */
const q = (d: string): string =>
  d.replace(/-?\d+\.\d+(?:e-?\d+)?/gi, (n) => String(Number(Number(n).toFixed(4))));

const dCache = new Map<string, string>();
export function dOf(entry: IconEntry): string {
  let d = dCache.get(entry.id);
  if (!d) {
    d =
      typeof entry.data === "string"
        ? entry.data
        : q(cubicsToPathD(iconToCubics(entry.data)));
    dCache.set(entry.id, d);
  }
  return d;
}
